config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resources :customers, except: :show
  resources :categories, except: :show do
    resources :products, only: [:new, :create]
  end

  resources :products, only: [:destroy, :edit, :update]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  require 'inventory_api'
  
  def index
    @categories = InventoryApi.get_all("categories")
  end

  def new
  end

  def create
    response = InventoryApi.post_to_server('categories', category_params)
    if response["errors"].nil?
      redirect_to categories_path 
    else
      error = response["errors"]
      redirect_to :back, :alert => error
    end
  end

  def edit
    @current_category = InventoryApi.get_one("categories", params[:id])
  end

  def update
    response = InventoryApi.patch_to_server('categories', category_params)
    if response["errors"].nil?
      redirect_to categories_path
    else
      error = response["errors"]
      redirect_to :back, :alert => error
    end
  end

  def destroy
    response = InventoryApi.delete_to_server('categories', params)
    redirect_to categories_path, notice: "Successfully delete category"
  end

private

  def category_params
    params.require(:category).permit(:id, :name, :description)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  require 'inventory_api'

  def index
    @customers = InventoryApi.get_all("customers")
  end

  def new
  end

  def create
    response = InventoryApi.post_to_server('customers',customer_params)
    if response["errors"].nil?
      redirect_to customers_path   
    else
      error = response["errors"]
      redirect_to :back, :alert => error
    end
  end

  def edit
    @current_customer = InventoryApi.get_one("customers", params[:id])["attributes"]
  end

  def update
    response = InventoryApi.patch_to_server('customers', customer_params)
    if response["errors"].nil?
      redirect_to customers_path
    else
      error = response["errors"]
      redirect_to :back, :alert => error
    end
  end

  def destroy
    response = InventoryApi.delete_to_server('customers', params)
    redirect_to customers_path, notice: "Successfully delete customer"
  end

  private

  def customer_params
    params.require(:customer).permit(:id, :name, :address, :country, :zip, :photo_id)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
  end

  def create
    response = InventoryApi.post_to_server("categories/#{product_params[:category_id]}/products", product_params)
    if response["errors"].nil?
      redirect_to categories_path 
    else
      error = response["errors"]
      redirect_to :back, :alert => error
    end
  end

  def edit
    categories = InventoryApi.get_all("categories")
    id = params[:id].to_i
    @current_product = []
    @categories_collection = categories.map do |a|
      m = (a["attributes"]["products"]).select{ |h| h["id"] == id }
      @current_product = m unless m.empty?
      [a["attributes"]["name"], a["id"]]
    end
  end

  def update
    response = InventoryApi.patch_to_server('products', product_params)
    if response["errors"].nil?
      redirect_to categories_path
    else
      error = response["errors"]
      redirect_to :back, :alert => error
    end
  end

  def destroy
    response = InventoryApi.delete_to_server('products', params)
    redirect_to categories_path, notice: "Successfully delete products"
  end

private

  def product_params
    params.require(:product).permit(:id, :category_id, :name, :price, :cost)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @home_page = true
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/edit.html.slim
= simple_form_for :category, url: category_path(id: params[:id]), :method => :patch, :html => {:'data-type' => 'json', :multipart => true}, wrapper: :inline_field4, defaults: {required: false} do |f|
  .row
    .col.s12
      #items_field
        i.small.material-icons store
        span Edit category
        .row
          = f.input :name, :input_html => { value: "#{@current_category["attributes"]["name"]}" }
          = f.input :description, :input_html => { value: "#{@current_category["attributes"]["description"]}" }
          = f.input :id, :as => :hidden, :input_html => { :value => params[:id] }
  .row
    .col.s12
      = f.button :button, class:"btn-large"
        i.material-icons.right cloud
        |
          Edit Category

app/views/categories/index.html.slim
h3 Categories

ul.collapsible.popout
  -@categories.each do |category|
    li
      .collapsible-header
        = category["attributes"]["name"]
        = link_to edit_category_path(category["id"]), :class => "right tooltipped", data:{ position: "left", delay: "50", tooltip: "Edit Category"}
          i.material-icons settings
        = link_to category_path(category["id"]), :class => "category_#{category["id"]} right", data:{ position: "right tooltipped", delay: "50", tooltip: "Delete Category"}, :confirm => 'Are your sure?', :method=> :delete
          i.material-icons delete
      .collapsible-body
        table.highlight
          tr
            th(class="first-column") Product Name
            th Selling Price
            th Cost
            th Product Description
            th(class="last-column") Action
          
          - category["attributes"]["products"].each do |product|
            tr 
              td(class="first-column") = product["name"]
              td = number_to_currency(product["price"], locale: 'en')
              td = number_to_currency(product["cost"], locale: 'en')
              td = product["description"]
              td(class="action")
                span.action.waves-effect.waves-red 
                  = link_to edit_product_path(:id => product["id"]), :class=>'tooltipped', data:{ position: "left", delay: "50", tooltip: "Edit Product"}, :confirm => 'Are your sure?'
                    i.material-icons.action equalizer
                span.action.waves-effect.waves-green
                  = link_to product_path(:id => product["id"]), :class=>"products_#{product["id"]} tooltipped", data:{ position: "left", delay: "50", tooltip: "Delete Product"}, :confirm => 'Are your sure?', :method=> :delete
                    i.material-icons.action clear
          tr
            td(colspan=5 class="first-column") = link_to new_category_product_path(category_id: category["id"]), :class=>'tooltipped', data:{ position: "right", delay: "50", tooltip: "Add new product"}
              i.material-icons add


.col.s4
  = button_to 'Go Back', root_path, method: :get, class: "btn"
.col.s4
  = button_to 'Add Category', new_category_path, method: :get, class: "btn"

app/views/categories/new.html.slim
= simple_form_for :category, url: categories_path, :html => {:'data-type' => 'json', :multipart => true}, wrapper: :inline_field4, defaults: {required: false} do |f|
  .row
    .col.s12
      #items_field
        i.small.material-icons store
        span Category
        .row
          = f.input :name, placeholder: "Category Name"
          = f.input :description, placeholder: "Description(optional)"
  .row
    .col.s12
      = f.button :button, class:"btn-large"
        i.material-icons.right cloud
        |
          Add Category

app/views/customers/edit.html.slim
= simple_form_for :customer, :url => customer_path(id: params[:id]), :method => :patch, :html => {:'data-type' => 'json', :multipart => true}, wrapper: :inline_field4, defaults: {required: false} do |f|
  .row
    .col.s12
      #items_field
        i.small.material-icons perm_identity
        span Edit customer
        .row
          = f.input :name, :input_html => { value: "#{@current_customer["name"]}" }
          = f.input :address, :input_html => { value: "#{@current_customer["address"]}" }
          = f.input :country, :as => :string, :input_html => { value: "#{@current_customer["country"]}" }         
        .row
          = f.input :zip_code, :input_html => { value: "#{@current_customer["zip_code"]}" }
          = f.input :photo_id, :input_html => { :type => "checkbox", :id => "photo_id_check", checked: @current_customer["photo_id"]}, wrapper: :inline_bool4, label: "Identification uploaded"
          = f.input :id, :as => :hidden, :input_html => { :value => params[:id] }
  .row
    .col.s12
      = f.button :button, class:"btn-large"
        i.material-icons.right cloud
        |
          Edit Customer

app/views/customers/index.html.slim
h3 Customers
  
table.highlight
  tr
    th Name
    th Address
    th zip-code
    th Identification
    th Add order
    th Edit customer
    th Delete customer

  - @customers.each do |customer|
    tr 
      td = link_to customer["attributes"]["name"], customer_path(customer["id"])
      td = customer["attributes"]["address"]
      td = customer["attributes"]["zip-code"]
      - if customer["attributes"]["photo_id"]
        td Yes
      - else
        td No
      td = link_to new_customer_path(customer["id"]), :class=>'tooltipped', data:{ position: "left", delay: "50", tooltip: "Add Customer"}
        i.material-icons add
      td = link_to edit_customer_path(customer["id"]), :class=>'tooltipped',  data:{ position: "top", delay: "50", tooltip: "Edit Customer"}
        i.material-icons settings
      td = link_to customer_path(customer["id"]), :class => "customer_#{customer["id"]} tooltipped", data:{ position: "right", delay: "50", tooltip: "Delete Customer"}, :confirm => 'Are your sure?', :method=> :delete
        i.material-icons delete
.col.s4
  = button_to 'Go Back', root_path, method: :get, class: "btn"
.col.s4  
  = button_to 'Add Customer', new_customer_path, method: :get, class: "btn"

app/views/customers/new.html.slim
= simple_form_for :customer, :url => customers_path, :html => {:'data-type' => 'json', :multipart => true}, wrapper: :inline_field4, defaults: {required: false} do |f|
  .row
    .col.s12
      #items_field
        i.small.material-icons perm_identity
        span New customer
        .row
          = f.input :name, placeholder: "Name"
          = f.input :address, placeholder: "Address"
          = f.input :country, :as => :string, placeholder: "Country"         
        .row
          = f.input :zip_code, placeholder: "Zip"
          = f.input :photo_id, :input_html => { :checked => "checked", :type => "checkbox", :id => "photo_id_check" }, wrapper: :inline_bool4, label: "Identification uploaded"
  .row
    .col.s12
      = f.button :button, class:"btn-large"
        i.material-icons.right cloud
        |
          CREATE CUSTOMER

app/views/layouts/application.html.slim
doctype html
html
  head
    title Inventory Control APP
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
  body id = "body#{@home_page ? '_homepage' : ''}"
    header
      nav
        .nav-wrapper
          =link_to "XiaoPutao", root_path, class:"brand-logo"
          ul.right.hide-on-med-and-down#nav-mobile
            li = link_to "Inventory", categories_path
            li = link_to "Customers", customers_path
            = render "shared/nav_dropdown"
            li(class="disable")
              a data-beloworigin="true" class="dropdown-button" data-activates="dropdown2"
                i.material-icons.right arrow_drop_down 
                | Logistics
            li(class="disable") 
              a data-beloworigin="true" class="dropdown-button" data-activates="dropdown1"
                i.material-icons.right arrow_drop_down 
                | Statistics

          a href="#" data-activates="slide-out" class="button-collapse"
            i.mdi-navigation-menu
    main
      .row
        .col.s10.offset-s1
          = render "shared/alert" unless flash[:alert].nil?
          = render "shared/notice" unless flash[:notice].nil?
          == yield
    footer id = "footer#{@home_page ? '_homepage' : ''}"
      .footer-copyright
        .container
          |
          2015 Copyright Text

app/views/products/edit.html.slim
= simple_form_for :product, url: product_path(id:params[:id]), :method => :patch, :html => {:'data-type' => 'json', :multipart => true}, wrapper: :inline_field4, defaults: {required: false} do |f|
  .row
    .col.s12
      #items_field
        i.small.material-icons store
        span Edit products
        .row
          = f.input :name, :input_html => { value: "#{@current_product.first["name"]}" }
          = f.input :price, :input_html => { value: "#{@current_product.first["price"]}" }
          = f.input :cost, :input_html => { value: "#{@current_product.first["cost"]}" }
        .row
          = f.input :category_id, collection: @categories_collection, label: "Category", include_blank: false, selected: @current_product.first["category_id"], :input_html => { :class => "browser-default" }
          = f.input :id, :as => :hidden, :input_html => { :value => params[:id] }
  .row
    .col.s12
      = f.button :button, class:"btn-large"
        i.material-icons.right cloud
        |
          Edit Product

app/views/products/new.html.slim
= simple_form_for :product, url: category_products_path(category_id:params[:category_id]), :html => {:'data-type' => 'json', :multipart => true}, wrapper: :inline_field4, defaults: {required: false} do |f|
  .row
    .col.s12
      #items_field
        i.small.material-icons store
        span New products
        .row
          = f.input :name, placeholder: "Product Name"
          = f.input :price, placeholder: "Current Sell Price $"
          = f.input :cost, placeholder: "Current Cost $"
          = f.input :category_id, :as => :hidden, :input_html => { :value => params[:category_id] }
  .row
    .col.s12
      = f.button :button, class:"btn-large"
        i.material-icons.right cloud
        |
          Add Products

app/views/shared/_alert.html.slim
.alert
  - flash[:alert].each do |m|
    div
      strong
        |Error! 
      = "#{m}"

app/views/shared/_nav_dropdown.html.slim
ul#dropdown1.dropdown-content
  li = link_to "View your charts"
  li = link_to "Red Alerts"
  li.divider
  li = link_to "Statements"
  
ul#dropdown2.dropdown-content
  li = link_to "Orders"
  li = link_to "Supplies"
  li = link_to "Shipments"

app/views/shared/_notice.html.slim
.alert.success
  strong
    |Notice! 
  = "#{flash[:notice]}"

app/views/static_pages/index.html.slim
#main-page